name: malleefowl
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=2.7
- setuptools=36.5.0
- pyopenssl
- cryptography
- libffi
- pyyaml
- curl
- icu=58
# buildout
- mako
# tests
- pytest
# pep8
- flake8
- pycodestyle
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
- doc8
# wps
- pywps=4.0.0
- owslib
- nginx=1.10.3
- supervisor=3.3
- gunicorn=19.7
- gevent=1.2
- eventlet
- lxml=3.7
- libxslt=1.1.29
- genshi
# malleefowl
- python-dateutil=2.6
- netcdf4=1.2.4
- requests
- esgf-pyclient=0.1.8
- myproxyclient=1.4.4
- dispel4py=1.0.1
- threddsclient=0.3.4
- pysolr=3.3.2
- wget
- pip:
  - sphinx-autoapi==0.4.0
