name: malleefowl
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pyopenssl
- cryptography
- libffi
- pyyaml
- curl
- icu=56
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=4.0.0
- owslib
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.2
- eventlet=0.19.0
- lxml=3.7
- libxslt=1.1.29
# malleefowl
- python-dateutil=2.6
- netcdf4=1.2.4
- requests
- esgf-pyclient=0.1.8
- dispel4py=1.0.1
- threddsclient=0.3.4
- pysolr=3.3.2
- wget=2.2
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
#  - eventlet==0.19.0
