name: malleefowl
channels:
- defaults
- birdhouse
- ioos
dependencies:
- python=2.7.12
- pyopenssl=0.16.0
- cryptography=1.4
- libffi
- pyyaml=3.11
- curl=7.45.0
# buildout
- mako=1.0.4
# tests
- pytest=2.9.2
# ipython
- ipython=4.2.0
# docs
- sphinx=1.4.1
- sphinx_rtd_theme
# wps
- pywps=3.2.6
- gdal=1.11.2
- lxml=3.6.0
- owslib=0.11.2
- nginx=1.10.1
- supervisor=3.1.3
- gunicorn=19.1.0
- gevent=1.1.1
- eventlet=0.16.1
# malleefowl
- python-dateutil=2.5.3
- netcdf4=1.2.4
- esgf-pyclient=0.1.6
- myproxyclient=1.4.3
- dispel4py=1.0.1
- python-swiftclient=2.4.0
- threddsclient=0.3.4
- pysolr=3.3.2
- wget=1.15
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
#  - eventlet==0.19.0
